# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    rule_testcase.mk                                   :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mamiyaza <mamiyaza@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/13 23:33:38 by mamiyaza          #+#    #+#              #
#    Updated: 2024/03/01 04:29:20 by mamiyaza         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Make rules
#  Make rules for testcases

leak:
	CALL_DESTRUCTOR=1
	make re -s
	make clean

test0:
	make re -s
	./$(NAME) $(TESTCASE0)
	make fclean

test1:
	make re -s
	./$(NAME) $(TESTCASE1)
	make fclean

test2:
	make re -s
	./$(NAME) $(TESTCASE2)
	make fclean

test_e:
	make re -s
	./$(NAME) $(ERROR_CASE_EMPTY_LINE)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES1)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES2)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES3)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES4)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES5)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES6)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES7)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES8)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES9)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES10)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES11)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES12)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES13)
	./$(NAME) $(ERROR_CASE_SIMPLE_VALUES14)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES0)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES1)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES2)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES3)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES4)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES5)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES6)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES7)
	./$(NAME) $(ERROR_CASE_PARAMETER_BOUNDARY_VALUES8)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER0)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER1)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER2)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER3)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER4)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER5)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER6)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER7)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER8)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER9)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER10)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER11)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER12)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER13)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER14)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER15)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER16)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER17)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER18)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER19)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER20)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER21)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER22)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER23)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER24)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER25)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER26)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER27)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER28)
	./$(NAME) $(ERROR_CASE_ATOI_SIGN_OF_NUMBER29)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES1)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES2)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES3)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES4)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES5)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES6)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES7)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES8)
	./$(NAME) $(ERROR_CASE_ATOI_EMPTY_LINE_AND_SPACES9)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS0)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS1)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS2)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS3)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS4)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS5)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS6)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS7)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS8)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS9)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS10)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS11)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS12)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS13)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS14)
	./$(NAME) $(ERROR_CASE_ATOI_NON_NUMERIC_CHARS15)
	make fclean

.PHONY: leak test0 test1 test2 test_e
